"""Resume section schema added

Revision ID: d4a12a2f8eb0
Revises: 0dc77ce08037
Create Date: 2026-07-20 23:24:59.568470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a12a2f8eb0'
down_revision: Union[str, Sequence[str], None] = '0dc77ce08037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('secure_url', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'secure_url')
    # ### end Alembic commands ###
