"""Added auto-update to update-time in resumes

Revision ID: f6bf18203a91
Revises: cc7303c9f7dd
Create Date: 2026-07-21 22:48:52.004557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6bf18203a91'
down_revision: Union[str, Sequence[str], None] = 'cc7303c9f7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
